# Generated by Django 4.0.1 on 2022-02-18 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_tag', models.CharField(db_index=True, max_length=50, verbose_name='Черта Характера.')),
            ],
            options={
                'verbose_name': 'Черта',
                'verbose_name_plural': 'Социальная Память -  Черты Характера',
                'ordering': ['char_tag'],
            },
        ),
        migrations.CreateModel(
            name='Constant_Expression',
            fields=[
                ('Const_Expr', models.TextField(primary_key=True, serialize=False, verbose_name='Утверждение')),
                ('Const_Type', models.CharField(choices=[('Very_Good', 'Очень Хорошо'), ('Good', 'Хорошо'), ('Neutral', 'Нейтрально'), ('Bad', 'Плохо'), ('Very_Bad', 'Очень плохо')], default='Neutral', max_length=12, verbose_name='Моральная Оценка')),
            ],
            options={
                'verbose_name': 'Утверждение',
                'verbose_name_plural': 'Постоянная Память - Константы',
                'ordering': ['Const_Expr'],
            },
        ),
        migrations.CreateModel(
            name='Context_Table',
            fields=[
                ('Context', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Контекст')),
                ('Context_Desc', models.TextField(verbose_name='Значение Контекста')),
            ],
            options={
                'verbose_name': 'Контекст',
                'verbose_name_plural': 'Постоянная Память - Контексты',
                'ordering': ['Context'],
            },
        ),
        migrations.CreateModel(
            name='Ego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.ImageField(null=True, upload_to='photo/Asiya/%Y/%m/%d', verbose_name='Облик')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('sur_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('age', models.FloatField(default=15, verbose_name='Возраст')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата Рождения')),
            ],
            options={
                'verbose_name': 'Данные Асии',
                'verbose_name_plural': 'Фундаментальная Память - Асия',
            },
        ),
        migrations.CreateModel(
            name='EM_Type',
            fields=[
                ('EMT', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Эпизодичская Память - Тип воспоминания',
                'ordering': ['EMT'],
            },
        ),
        migrations.CreateModel(
            name='Emote_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emote_Name', models.CharField(db_index=True, max_length=100, verbose_name='Код Чувства')),
                ('ET_Type', models.CharField(choices=[('Creature', 'Сущность'), ('None', 'Неопределенный'), ('Ivent', 'Событие'), ('Object', 'Объект')], default='None', max_length=14, verbose_name='Тип Причины')),
                ('ET_Descript', models.TextField(blank=True, null=True, verbose_name='Описание Причины.')),
                ('ET_Date', models.DateField(auto_now_add=True, verbose_name='Дата Возникновения')),
                ('Horror', models.FloatField(default=0.0, verbose_name='Ужас')),
                ('Anxiety', models.FloatField(default=0.0, verbose_name='Тревога')),
                ('Concern', models.FloatField(default=0.0, verbose_name='Беспокойство')),
                ('Astonishment', models.FloatField(default=0.0, verbose_name='Удивление')),
                ('Confusion', models.FloatField(default=0.0, verbose_name='Замешательство')),
                ('Timidity', models.FloatField(default=0.0, verbose_name='Робость')),
                ('Guilt', models.FloatField(default=0.0, verbose_name='Вина')),
                ('Embarrassment', models.FloatField(default=0.0, verbose_name='Смущение')),
                ('Doubt', models.FloatField(default=0.0, verbose_name='Сомнение')),
                ('Rage', models.FloatField(default=0.0, verbose_name='Ярость')),
                ('Irritation', models.FloatField(default=0.0, verbose_name='Раздражение')),
                ('Resentment', models.FloatField(default=0.0, verbose_name='Обида')),
                ('Disgust', models.FloatField(default=0.0, verbose_name='Отвращение')),
                ('Jealousy', models.FloatField(default=0.0, verbose_name='Ревность')),
                ('Envy', models.FloatField(default=0.0, verbose_name='Зависть')),
                ('Indignation', models.FloatField(default=0.0, verbose_name='Возмущение')),
                ('Nervousness', models.FloatField(default=0.0, verbose_name='Нервозность')),
                ('Disappointment', models.FloatField(default=0.0, verbose_name='Разочарование')),
                ('Idleness', models.FloatField(default=0.0, verbose_name='Лень')),
                ('Despait', models.FloatField(default=0.0, verbose_name='Отчаяние')),
                ('Compassion', models.FloatField(default=0.0, verbose_name='Жалость')),
                ('Loneliness', models.FloatField(default=0.0, verbose_name='Отрешенность')),
                ('Helplessness', models.FloatField(default=0.0, verbose_name='Беспомощность')),
                ('Aloofness', models.FloatField(default=0.0, verbose_name='Отчужденность')),
                ('Regret', models.FloatField(default=0.0, verbose_name='Сожаление')),
                ('Boredom', models.FloatField(default=0.0, verbose_name='Скука')),
                ('Sadness', models.FloatField(default=0.0, verbose_name='Печаль')),
                ('Happiness', models.FloatField(default=0.0, verbose_name='Счастье')),
                ('Delight', models.FloatField(default=0.0, verbose_name='Восторг')),
                ('Interest', models.FloatField(default=0.0, verbose_name='Интерес')),
                ('Excitement', models.FloatField(default=0.0, verbose_name='Возбуждение')),
                ('Curiosity', models.FloatField(default=0.0, verbose_name='Любопытство')),
                ('Confidence', models.FloatField(default=0.0, verbose_name='Уверенность')),
                ('Horny', models.FloatField(default=0.0, verbose_name='Хорни')),
                ('Laugh', models.FloatField(default=0.0, verbose_name='Смех')),
                ('Satisfaction', models.FloatField(default=0.0, verbose_name='Удовлетворение')),
            ],
            options={
                'verbose_name': 'Чувство',
                'verbose_name_plural': 'Социальная Память - Архив Эмоций',
                'ordering': ['Emote_Name'],
            },
        ),
        migrations.CreateModel(
            name='GOW',
            fields=[
                ('COW', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Категория Слов')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Постоянная Память - Группирование Слов',
                'ordering': ['COW'],
            },
        ),
        migrations.CreateModel(
            name='Like_Dislike',
            fields=[
                ('subject', models.TextField(primary_key=True, serialize=False, verbose_name='Объект')),
                ('Reg_Date', models.DateField(auto_now_add=True)),
                ('rel_to', models.CharField(choices=[('Like', 'Нравится'), ('Neutral', 'Нейтрально'), ('Dislike', 'Не нравится')], default='Neutral', max_length=10, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Предпочтения',
                'verbose_name_plural': 'Личностная Память - Предпочтения',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Motives',
            fields=[
                ('Aspiration', models.TextField(primary_key=True, serialize=False, verbose_name='Стремление')),
                ('Reg_Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Личностная Память - Желания',
                'ordering': ['Aspiration'],
            },
        ),
        migrations.CreateModel(
            name='Person_Memory',
            fields=[
                ('unic_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True, verbose_name='Имя')),
                ('sur_name', models.CharField(max_length=40, null=True, verbose_name='Фамилия')),
                ('appearance', models.ImageField(null=True, upload_to='photo/%Y/%m', verbose_name='Внешний Вид')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата Рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('None', 'Неопределен'), ('female', 'Женский')], default='None', max_length=6, verbose_name='Пол')),
                ('affection', models.FloatField(default=0.0, null=True, verbose_name='Любовь')),
                ('sympathy', models.FloatField(default=0.0, null=True, verbose_name='Симпатия')),
                ('friendship', models.FloatField(default=0.0, null=True, verbose_name='Дружба')),
                ('admiration', models.FloatField(default=0.0, null=True, verbose_name='Восхищение')),
                ('mania', models.FloatField(default=0.0, null=True, verbose_name='Мания')),
                ('abhorrence', models.FloatField(default=0.0, null=True, verbose_name='Ненависть')),
                ('spite', models.FloatField(default=0.0, null=True, verbose_name='Враждебность')),
                ('disaffection', models.FloatField(default=0.0, null=True, verbose_name='Неприязнь')),
                ('fright', models.FloatField(default=0.0, null=True, verbose_name='Страх')),
                ('rep_sum', models.FloatField(blank=True, null=True, verbose_name='Балл Взаимоотношений.')),
                ('meet_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата Знакомства')),
                ('fund_description', models.TextField(blank=True, null=True, verbose_name='Краткое Описание')),
                ('local_description', models.TextField(blank=True, null=True, verbose_name='Наблюдения Асии')),
                ('char_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CharOne', to='Asiya.character_tags', verbose_name='Черта Характера (1) - ')),
                ('char_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CharTwo', to='Asiya.character_tags', verbose_name='Черта Характера (2) - ')),
                ('char_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CharThree', to='Asiya.character_tags', verbose_name='Черта Характера (3) - ')),
            ],
            options={
                'verbose_name': 'Сущность',
                'verbose_name_plural': 'Социальная Память - Личности',
                'ordering': ['meet_date'],
            },
        ),
        migrations.CreateModel(
            name='Postulates',
            fields=[
                ('Postul', models.TextField(primary_key=True, serialize=False, verbose_name='Постулат')),
                ('Reg_Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Постулат',
                'verbose_name_plural': 'Личностная Память - Постулаты',
                'ordering': ['Postul'],
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relation', models.CharField(db_index=True, max_length=50, verbose_name='Тип Отношений.')),
            ],
            options={
                'verbose_name': 'Отношение',
                'verbose_name_plural': 'Социальная Память - Взаимотношения',
                'ordering': ['Relation'],
            },
        ),
        migrations.CreateModel(
            name='VM_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, verbose_name='Слово')),
                ('polysemantic', models.BooleanField(default=False, verbose_name='Многозначность')),
                ('constant_w', models.BooleanField(default=False, verbose_name='Константа')),
                ('nomination', models.BooleanField(default=False, verbose_name='Слово - Наименование?')),
                ('word_type', models.CharField(choices=[('Motion', 'Глагол'), ('Descriptor', 'Прилагательное'), ('NOUN', 'Существительное'), ('STATE', 'Состояние'), ('NOMIN', 'Местоимение'), ('SOUND', 'Звук')], default='NOUN', max_length=16, verbose_name='Тип слова')),
                ('word_gender', models.CharField(choices=[('Male', 'Мужской'), ('Neutral', 'Средний'), ('Female', 'Женский')], default='Neutral', max_length=16, verbose_name='Род слова')),
                ('word_des', models.TextField(blank=True, null=True, verbose_name='Значение слова')),
                ('associate_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AW', to='Asiya.vm_word', verbose_name='Слово Ассоциация')),
                ('group_of_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GOW', to='Asiya.gow', verbose_name='Группировка Слов')),
                ('synonym_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SynW', to='Asiya.vm_word', verbose_name='Слово Синоним')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Постоянная Память - Вербальная Память',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Sentence_Memory',
            fields=[
                ('Sentence', models.TextField(primary_key=True, serialize=False, verbose_name='Предложение')),
                ('Sent_Dech', models.TextField(verbose_name='Код-Дешифровка предложения')),
                ('Short_Mean', models.TextField(blank=True, null=True, verbose_name='Краткая суть')),
                ('From_Who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.person_memory', verbose_name='Источник Предложения')),
                ('Sent_Context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.context_table', verbose_name='Контекст предложения')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Постоянная Память - Предложения',
                'ordering': ['Sentence'],
            },
        ),
        migrations.CreateModel(
            name='Semantic_Memory',
            fields=[
                ('DON', models.DateField(auto_now_add=True, verbose_name='Дата Занесения')),
                ('VON', models.FloatField(default=0.0, verbose_name='Доверие к записи')),
                ('Note', models.TextField(primary_key=True, serialize=False, verbose_name='Запись')),
                ('SON', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.person_memory', verbose_name='Источник Записи')),
            ],
            options={
                'verbose_name': 'Знание',
                'verbose_name_plural': 'Постоянная Память - Семантическая Память',
                'ordering': ['DON'],
            },
        ),
        migrations.AddField(
            model_name='person_memory',
            name='relation_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RelFrom', to='Asiya.relationtype', verbose_name='Отношение Сущности к Асии:'),
        ),
        migrations.AddField(
            model_name='person_memory',
            name='relation_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RelTo', to='Asiya.relationtype', verbose_name='Отношение Асии к Сущности:'),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_index=True, verbose_name='Заключение')),
                ('Reg_Date', models.DateField(auto_now_add=True)),
                ('Current_Motive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.motives', verbose_name='Мотив')),
                ('Emote_Condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.emote_reg', verbose_name='Эмоциональнео состояние')),
            ],
            options={
                'verbose_name': 'Синапс',
                'verbose_name_plural': 'Личностная Память - Эго Асии',
                'ordering': ['Reg_Date'],
            },
        ),
        migrations.CreateModel(
            name='Episode_Memory',
            fields=[
                ('Episode', models.TextField(primary_key=True, serialize=False, verbose_name='Содержание Воспоминания')),
                ('DOR', models.DateField(auto_now_add=True, verbose_name='Дата Приобретения')),
                ('Emote_Score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Asiya.emote_reg', verbose_name='Испытываемые Эмоции')),
                ('Emote_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.em_type', verbose_name='Тип Воспоминания')),
                ('Share_With', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Asiya.person_memory', verbose_name='С кем разделяет')),
            ],
            options={
                'verbose_name': 'Воспоминание',
                'verbose_name_plural': 'Постоянная Память - Эпизодическая Память',
                'ordering': ['Share_With'],
            },
        ),
        migrations.AddField(
            model_name='emote_reg',
            name='Emote_Trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ETrig', to='Asiya.person_memory', verbose_name='Кто Причина'),
        ),
    ]
