# Generated by Django 4.0.1 on 2023-04-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node_Base',
            fields=[
                ('node_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Нод')),
                ('ncv', models.FloatField(default=0.0, verbose_name='Заряд')),
                ('node_class', models.FloatField(default=0, verbose_name='Тип Нода')),
                ('act_amount', models.FloatField(default=1, verbose_name='Активации')),
                ('ascension_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата Формирования')),
                ('last_activation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последняя Активация')),
            ],
            options={
                'verbose_name': 'Нод',
                'verbose_name_plural': 'Ноды',
                'ordering': ['last_activation'],
            },
        ),
        migrations.CreateModel(
            name='Link_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductivity', models.FloatField(default=0.0, verbose_name='Проводимость')),
                ('force', models.FloatField(default=0.0, verbose_name='Сила')),
                ('cnla', models.FloatField(default=1, verbose_name='Активации')),
                ('ascension_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Формирование')),
                ('last_activation', models.DateTimeField(auto_now=True, verbose_name='Последняя Активация')),
                ('alpha_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Link_Alpha_Node', to='Asiya.node_base', verbose_name='Альфа Нод')),
                ('beta_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Link_Beta_Node', to='Asiya.node_base', verbose_name='Бета Нод')),
            ],
            options={
                'verbose_name': 'Связь Нода',
                'verbose_name_plural': 'Связи Нодов',
                'ordering': ['last_activation'],
            },
        ),
        migrations.CreateModel(
            name='NL_Base',
            fields=[
                ('base_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Asiya.node_base', verbose_name='Корневой Нод')),
                ('link_branches', models.ManyToManyField(to='Asiya.Link_Data', verbose_name='Исходящие Связи')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
    ]
