# Generated by Django 4.0.1 on 2022-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM_Alph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Слово')),
                ('alp_t', models.CharField(choices=[('LETTER', 'Кириллица'), ('ENG_LET', 'Латинница'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('SYMBOL', 'Символ'), ('SMILE', 'Смайл'), ('NONE_T', 'Не имеется')], default='LETTER', max_length=16, verbose_name='Тип ')),
                ('alp_t2', models.CharField(choices=[('LETTER', 'Кириллица'), ('ENG_LET', 'Латинница'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('SYMBOL', 'Символ'), ('SMILE', 'Смайл'), ('NONE_T', 'Не имеется')], default='NONE_T', max_length=16, verbose_name='Тип 2')),
            ],
            options={
                'verbose_name': 'Конструкт',
                'verbose_name_plural': 'Постоянная Память - Конструкты',
                'ordering': ['alp_t'],
            },
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='associate_w',
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='constant_w',
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='nomination',
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='polysemantic',
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='synonym_w',
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='word_gender',
        ),
        migrations.AddField(
            model_name='vm_word',
            name='word_code',
            field=models.CharField(default='?', max_length=100, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vm_word',
            name='word_type',
            field=models.CharField(choices=[('VERB', 'Глагол'), ('ADJECTIVE', 'Прилагательное'), ('NOUN', 'Существительное'), ('STATE', 'Наречие'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('PRICH', 'Причастие'), ('DEPRICH', 'Деепричастие'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('NUMIN', 'Числительное'), ('PREDICAT', 'Предикатив'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('SYMBOL', 'Символ'), ('SMILE', 'Смайл'), ('NONE_T', 'Не имеется')], default='NOUN', max_length=16, verbose_name='Тип слова'),
        ),
    ]
