# Generated by Django 4.0.1 on 2023-04-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link_data',
            options={'ordering': ['last_activation'], 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterModelOptions(
            name='nl_base',
            options={'verbose_name': 'Связь Нода', 'verbose_name_plural': 'Связи Нодов'},
        ),
        migrations.AlterField(
            model_name='nl_base',
            name='link_branches',
            field=models.ManyToManyField(to='Asiya.Link_Data', verbose_name='Принадлежные Связи Связи'),
        ),
    ]
