# Generated by Django 4.0.1 on 2022-03-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationtype',
            options={'ordering': ['relation'], 'verbose_name': 'Отношение', 'verbose_name_plural': 'Социальная Память - Взаимотношения'},
        ),
        migrations.RenameField(
            model_name='relationtype',
            old_name='Relation',
            new_name='relation',
        ),
    ]
