# Generated by Django 4.0.1 on 2022-02-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_word',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Слово'),
        ),
    ]
