# Generated by Django 4.0.1 on 2022-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ego',
            name='age',
            field=models.FloatField(default=16, verbose_name='Возраст'),
        ),
    ]
