# Generated by Django 4.0.1 on 2022-02-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ego',
            name='Appearance',
            field=models.ImageField(null=True, upload_to='photo/Asiya/%Y/%m/%d', verbose_name='Облик'),
        ),
        migrations.AddField(
            model_name='person_memory',
            name='Appearance',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d', verbose_name='Внешний Вид'),
        ),
    ]
