# Generated by Django 4.0.1 on 2023-04-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0002_alter_link_data_options_alter_nl_base_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NL_Base',
        ),
    ]
