# Generated by Django 4.0.1 on 2022-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0002_ego_appearance_person_memory_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_memory',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
    ]
