# Generated by Django 4.0.1 on 2022-02-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0003_alter_vm_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_word',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Слово'),
        ),
    ]
