# Generated by Django 4.0.1 on 2022-02-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0003_alter_person_memory_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_memory',
            name='Abhorrence',
            field=models.FloatField(default=0.0, null=True, verbose_name='Ненависть'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='Admiration',
            field=models.FloatField(default=0.0, null=True, verbose_name='Восхищение'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='Affection',
            field=models.FloatField(default=0.0, null=True, verbose_name='Любовь'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='DisAffection',
            field=models.FloatField(default=0.0, null=True, verbose_name='Неприязнь'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='FriendShip',
            field=models.FloatField(default=0.0, null=True, verbose_name='Дружба'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='Fright',
            field=models.FloatField(default=0.0, null=True, verbose_name='Страх'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='Mania',
            field=models.FloatField(default=0.0, null=True, verbose_name='Мания'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='Spite',
            field=models.FloatField(default=0.0, null=True, verbose_name='Враждебность'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='Sympathy',
            field=models.FloatField(default=0.0, null=True, verbose_name='Симпатия'),
        ),
    ]
