# Generated by Django 4.0.1 on 2023-04-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0003_delete_nl_base'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link_Data',
            new_name='NL_Base',
        ),
    ]
