# Generated by Django 4.0.1 on 2022-03-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0003_vm_word_mult_vm_word_word_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vm_word',
            old_name='Mult',
            new_name='mult',
        ),
    ]
