# Generated by Django 4.0.1 on 2022-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0004_alter_person_memory_abhorrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_memory',
            name='Meet_Date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата Знакомства'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='first_name',
            field=models.CharField(max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person_memory',
            name='sur_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Фамилия'),
        ),
    ]
