# Generated by Django 4.0.1 on 2023-04-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0004_rename_link_data_nl_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductivity', models.FloatField(default=0.0, verbose_name='Проводимость')),
                ('force', models.FloatField(default=0.0, verbose_name='Сила')),
                ('cnla', models.FloatField(default=1, verbose_name='Активации')),
                ('ascension_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Формирование')),
                ('last_activation', models.DateTimeField(auto_now=True, verbose_name='Последняя Активация')),
                ('alpha_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Link_Alpha_Point', to='Asiya.node_base', verbose_name='Альфа Нод')),
                ('beta_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Link_Beta_Point', to='Asiya.node_base', verbose_name='Бета Нод')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'ordering': ['last_activation'],
            },
        ),
        migrations.DeleteModel(
            name='NL_Base',
        ),
    ]
