# Generated by Django 4.0.1 on 2022-02-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0005_alter_person_memory_meet_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person_memory',
            options={'ordering': ['meet_date'], 'verbose_name': 'Сущность', 'verbose_name_plural': 'Социальная Память - Личности'},
        ),
        migrations.RenameField(
            model_name='ego',
            old_name='Appearance',
            new_name='appearance',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Abhorrence',
            new_name='abhorrence',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Admiration',
            new_name='admiration',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Affection',
            new_name='affection',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Appearance',
            new_name='appearance',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Char_1',
            new_name='char_1',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Char_2',
            new_name='char_2',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Char_3',
            new_name='char_3',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='DisAffection',
            new_name='disaffection',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='FriendShip',
            new_name='friendShip',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Fright',
            new_name='fright',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Fund_Description',
            new_name='fund_description',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Local_Description',
            new_name='local_description',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Mania',
            new_name='mania',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Meet_Date',
            new_name='meet_date',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Relation_To',
            new_name='relation_to',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Rep_SUM',
            new_name='rep_sum',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Spite',
            new_name='spite',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Sympathy',
            new_name='sympathy',
        ),
        migrations.RenameField(
            model_name='person_memory',
            old_name='Relation_From',
            new_name='telation_from',
        ),
    ]
