# Generated by Django 4.0.1 on 2022-02-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0006_alter_vm_word_word_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_word',
            name='word_gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Neutral', 'Средний'), ('NONE', 'Без рода'), ('Female', 'Женский')], default='NONE', max_length=16, verbose_name='Род слова'),
        ),
    ]
