# Generated by Django 4.0.1 on 2023-05-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0006_node_link_base_delete_link_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGCL',
            fields=[
                ('ng_code', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Код Группы')),
                ('ncl', models.ManyToManyField(related_name='Node_Construct_List', to='Asiya.Node_Base', verbose_name='Конструкт Лист Нодов')),
                ('nlcl', models.ManyToManyField(related_name='Node_Link_Construct_List', to='Asiya.Node_Base', verbose_name='Конструкт Лист Нод Линков')),
            ],
            options={
                'verbose_name': 'Конструкт Нод Группы',
                'verbose_name_plural': 'Конструкты Нод Группы',
                'ordering': ['ng_code'],
            },
        ),
        migrations.CreateModel(
            name='NG_Base',
            fields=[
                ('group_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Название Группы')),
                ('status', models.CharField(choices=[('solid', 'Цельная'), ('broken', 'Сломанная')], max_length=6, verbose_name='статус')),
                ('act_amount', models.FloatField(default=1, verbose_name='Активации')),
                ('distribution', models.FloatField(default=0, verbose_name='Распространенность')),
                ('ngx', models.FloatField(default=0.0, verbose_name='X координата')),
                ('ngy', models.FloatField(default=0.0, verbose_name='Y координата')),
                ('ngz', models.FloatField(default=0.0, verbose_name='Z координата')),
                ('ascension_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата Формирования')),
                ('last_activation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последняя Активация')),
                ('ngcl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Node_Group_Construct_List', to='Asiya.ngcl', verbose_name='Конструкты Нод Группы')),
            ],
            options={
                'verbose_name': 'Нод Группа',
                'verbose_name_plural': 'Нод Группы',
                'ordering': ['last_activation'],
            },
        ),
    ]
