# Generated by Django 4.0.1 on 2022-03-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0006_alter_vm_word_word_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_word',
            name='word_type',
            field=models.CharField(choices=[('Motion', 'Глагол'), ('Descriptor', 'Прилагательное'), ('NOUN', 'Существительное'), ('STATE', 'Состояние'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('SYMBOL', 'Символ')], default='NOUN', max_length=16, verbose_name='Тип слова'),
        ),
    ]
