# Generated by Django 4.0.1 on 2022-02-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0007_rename_telation_from_person_memory_relation_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_memory',
            old_name='friendShip',
            new_name='friendship',
        ),
    ]
