# Generated by Django 4.0.1 on 2023-05-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0007_ngcl_ng_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngcl',
            name='nlcl',
            field=models.ManyToManyField(related_name='Node_Link_Construct_List', to='Asiya.Node_Link_Base', verbose_name='Конструкт Лист Нод Линков'),
        ),
    ]
