# Generated by Django 4.0.1 on 2022-02-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0007_alter_vm_word_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_word',
            name='word_type',
            field=models.CharField(choices=[('Motion', 'Глагол'), ('Descriptor', 'Прилагательное'), ('NOUN', 'Существительное'), ('STATE', 'Состояние'), ('NOMIN', 'Местоимение'), ('SOUND', 'Звук'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число')], default='NOUN', max_length=16, verbose_name='Тип слова'),
        ),
    ]
