# Generated by Django 4.0.1 on 2022-03-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0007_alter_vm_word_word_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm_word',
            name='mult',
        ),
        migrations.AddField(
            model_name='vm_word',
            name='antonym_w',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AntW', to='Asiya.vm_word', verbose_name='Слово Антоним'),
        ),
        migrations.AddField(
            model_name='vm_word',
            name='w_compar',
            field=models.CharField(choices=[('POSIT', 'Положительная'), ('COMPAR', 'Сравнительная'), ('SUPER', 'Превосходная'), ('None', 'Нет степени.')], default='None', max_length=16, verbose_name='Степень Сравнения'),
        ),
        migrations.AddField(
            model_name='vm_word',
            name='w_inclin',
            field=models.CharField(choices=[('INDIC', 'Индикатив'), ('SUBINDIC', 'Субьюнктив'), ('IMPER', 'Императив'), ('None', 'Нет Наклонения')], default='None', max_length=16, verbose_name='Наклонение'),
        ),
        migrations.AddField(
            model_name='vm_word',
            name='w_mult',
            field=models.CharField(choices=[('PLURAL', 'Множественное'), ('SINGULAR', 'Единственное'), ('None', 'Не исчисляемо')], default='None', max_length=16, verbose_name='Число'),
        ),
        migrations.AddField(
            model_name='vm_word',
            name='w_spesh',
            field=models.CharField(choices=[('ANIMA', 'Одушевленный'), ('INANIMA', 'Неодушевленный'), ('None', 'Ничего.')], default='None', max_length=16, verbose_name='Одушевленность'),
        ),
        migrations.AddField(
            model_name='vm_word',
            name='w_time',
            field=models.CharField(choices=[('PLURAL', 'Настоящее'), ('SINGULAR', 'Прошлое'), ('FUTURE', 'Будущее'), ('None', 'Нет времени.')], default='None', max_length=16, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='vm_word',
            name='wt_secondary',
            field=models.CharField(choices=[('VERB', 'Глагол'), ('ADJECTIVE', 'Прилагательное'), ('NOUN', 'Существительное'), ('STATE', 'Наречие'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('PRICH', 'Причастие'), ('DEPRICH', 'Деепричастие'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('NUMIN', 'Числительное'), ('PREDICAT', 'Предикатив'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('SYMBOL', 'Символ'), ('NONE_T', 'Не имеется')], default='NONE_T', max_length=20, verbose_name='Адаптивная часть речи'),
        ),
        migrations.AlterField(
            model_name='vm_word',
            name='word_type',
            field=models.CharField(choices=[('VERB', 'Глагол'), ('ADJECTIVE', 'Прилагательное'), ('NOUN', 'Существительное'), ('STATE', 'Наречие'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('PRICH', 'Причастие'), ('DEPRICH', 'Деепричастие'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('NUMIN', 'Числительное'), ('PREDICAT', 'Предикатив'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('SYMBOL', 'Символ'), ('NONE_T', 'Не имеется')], default='NOUN', max_length=20, verbose_name='Часть Речи'),
        ),
    ]
