# Generated by Django 4.0.1 on 2022-02-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0009_alter_vm_word_word_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence_memory',
            options={'ordering': ['sentence'], 'verbose_name': 'Предложение', 'verbose_name_plural': 'Постоянная Память - Предложения'},
        ),
        migrations.RenameField(
            model_name='sentence_memory',
            old_name='From_Who',
            new_name='from_who',
        ),
        migrations.RenameField(
            model_name='sentence_memory',
            old_name='Sent_Context',
            new_name='sent_context',
        ),
        migrations.RenameField(
            model_name='sentence_memory',
            old_name='Sent_Dech',
            new_name='sent_dech',
        ),
        migrations.RenameField(
            model_name='sentence_memory',
            old_name='Sentence',
            new_name='sentence',
        ),
        migrations.RenameField(
            model_name='sentence_memory',
            old_name='Short_Mean',
            new_name='short_mean',
        ),
    ]
