# Generated by Django 4.0.1 on 2022-03-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0009_alter_vm_word_word_type_alter_vm_word_wt_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm_word',
            name='w_soul',
            field=models.CharField(choices=[('ANIMA', 'Одушевленный'), ('INANIMA', 'Неодушевленный'), ('None', 'Ничего.')], default='None', max_length=16, verbose_name='Одушевленность'),
        ),
        migrations.AlterField(
            model_name='vm_word',
            name='w_spesh',
            field=models.CharField(choices=[('PERFECT', 'Совершенный'), ('IMPERFECT', 'Несовершенный'), ('None', 'Нет Вида.')], default='None', max_length=16, verbose_name='Вид'),
        ),
    ]
