# Generated by Django 4.0.1 on 2022-03-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0010_vm_word_w_soul_alter_vm_word_w_spesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm_word',
            name='w_face',
            field=models.CharField(choices=[('FIRST', 'Первое'), ('SECOND', 'Второе'), ('THIRD', 'Третье'), ('None', 'Нет Лица.')], default='None', max_length=16, verbose_name='Лицо.'),
        ),
    ]
