# Generated by Django 4.0.1 on 2022-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asiya', '0012_vm_word_w_declin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_word',
            name='w_declin',
            field=models.CharField(choices=[('FIRST', 'Первое'), ('SECOND', 'Второе'), ('THIRD', 'Третье'), ('None', 'Нет склонения')], default='None', max_length=16, verbose_name='Склонение'),
        ),
    ]
