# Generated by Django 4.0.1 on 2022-04-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(db_index=True, max_length=50, verbose_name='Контекст')),
            ],
            options={
                'verbose_name': 'Контекст',
                'verbose_name_plural': 'Постоянная Память - Контексты',
                'ordering': ['context'],
            },
        ),
        migrations.CreateModel(
            name='GOW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Категория Слов')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Постоянная Память - Группирование Слов',
                'ordering': ['cow'],
            },
        ),
        migrations.CreateModel(
            name='VM_Alph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Слово')),
                ('alp_t', models.CharField(choices=[('LETTER', 'Кириллица'), ('ENG_LET', 'Латинница'), ('NOMIN', 'Местоимение'), ('INTER', 'Междометие'), ('UNION', 'Союз'), ('PREPOS', 'Предлог'), ('PUNCTATION', 'Пунктуация'), ('NUM', 'Число'), ('SYMBOL', 'Символ'), ('SMILE', 'Смайл'), ('NONE_T', 'Не имеется')], default='LETTER', max_length=16, verbose_name='Тип ')),
            ],
            options={
                'verbose_name': 'Конструкт',
                'verbose_name_plural': 'Постоянная Память - Конструкты',
                'ordering': ['alp_t'],
            },
        ),
        migrations.CreateModel(
            name='VM_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Слово')),
                ('word_code', models.CharField(max_length=100, verbose_name='Код')),
                ('x_cord', models.FloatField(verbose_name='X Координата')),
                ('y_cord', models.FloatField(verbose_name='Y Координата')),
                ('special_field', models.CharField(max_length=150, verbose_name='Спец Поле')),
                ('group_of_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GOW', to='Prima_Word.gow', verbose_name='Группировка Слов')),
            ],
            options={
                'verbose_name': 'Слова',
                'verbose_name_plural': 'Хранилище Слов',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Sentence_Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(db_index=True, unique=True, verbose_name='Предложение')),
                ('sent_dech', models.TextField(verbose_name='Код-Дешифровка предложения')),
                ('x_cord', models.FloatField(verbose_name='X Координата')),
                ('y_cord', models.FloatField(verbose_name='Y Координата')),
                ('special_field', models.CharField(max_length=150, verbose_name='Спец Поле')),
                ('sent_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prima_Word.context_table', verbose_name='Контекст предложения')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Постоянная Память - Предложения',
                'ordering': ['sentence'],
            },
        ),
    ]
