# Generated by Django 4.0.1 on 2022-05-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prima_Word', '0005_alter_vm_word_word_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vm_word',
            options={'ordering': ['word_type'], 'verbose_name': 'Слова', 'verbose_name_plural': 'Хранилище Слов'},
        ),
        migrations.RemoveField(
            model_name='vm_word',
            name='group_of_word',
        ),
    ]
