# Generated by Django 4.0.1 on 2022-05-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prima_Word', '0006_alter_vm_word_options_remove_vm_word_group_of_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correct_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sent', models.TextField(verbose_name='Предложение Пользователя')),
                ('us_dech', models.TextField(verbose_name='Код-Дешифровка US')),
                ('actual_resp', models.TextField(db_index=True, unique=True, verbose_name='Корректный Ответ.')),
                ('ar_dech', models.TextField(verbose_name='Код-Дешифровка AR')),
                ('g1', models.FloatField(default=5.0, verbose_name='Структура')),
                ('g2', models.FloatField(default=5.0, verbose_name='Грамматика')),
                ('g3', models.FloatField(default=10.0, verbose_name='Локальная Универсальность')),
                ('g4', models.FloatField(default=10.0, verbose_name='Глобальная Универсальность')),
                ('g5', models.FloatField(default=10.0, verbose_name='МоноРезистентность')),
                ('g6', models.FloatField(default=5.0, verbose_name='Осмысленность')),
                ('g7', models.BooleanField(default=False, verbose_name='Завершенность')),
                ('g8', models.BooleanField(default=False, verbose_name='Гибкая Дополняемость.')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Постоянная Память - Корректные предложения.',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='GOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cos', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Категория Слов')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Постоянная Память - Категории Предложений.',
                'ordering': ['cos'],
            },
        ),
        migrations.DeleteModel(
            name='GOW',
        ),
        migrations.DeleteModel(
            name='Sentence_Memory',
        ),
        migrations.AddField(
            model_name='correct_answers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GOS', to='Prima_Word.gos', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='correct_answers',
            name='sent_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prima_Word.context_table', verbose_name='Контекст'),
        ),
    ]
