# Generated by Django 4.0.1 on 2022-05-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prima_Word', '0007_correct_answers_gos_delete_gow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correct_answers',
            name='actual_resp',
            field=models.TextField(db_index=True, verbose_name='Корректный Ответ.'),
        ),
    ]
