# Generated by Django 4.0.1 on 2022-05-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prima_Word', '0008_alter_correct_answers_actual_resp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_resp', models.TextField(db_index=True, verbose_name='Мусорный Ответ.')),
                ('ar_dech', models.TextField(verbose_name='Код-Дешифровка AR')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Постоянная Память - Мусорные предложения.',
                'ordering': ['actual_resp'],
            },
        ),
        migrations.CreateModel(
            name='incorrect_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_resp', models.TextField(db_index=True, verbose_name='Ответ.')),
                ('ar_dech', models.TextField(verbose_name='Код-Дешифровка AR')),
                ('g1', models.FloatField(default=5.0, verbose_name='Структура')),
                ('g2', models.FloatField(default=5.0, verbose_name='Грамматика')),
                ('g3', models.FloatField(default=10.0, verbose_name='Локальная Универсальность')),
                ('g4', models.FloatField(default=10.0, verbose_name='Глобальная Универсальность')),
                ('g5', models.FloatField(default=10.0, verbose_name='МоноРезистентность')),
                ('g6', models.FloatField(default=5.0, verbose_name='Осмысленность')),
                ('g7', models.BooleanField(default=False, verbose_name='Завершенность')),
                ('g8', models.BooleanField(default=False, verbose_name='Гибкая Дополняемость.')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GOSI', to='Prima_Word.gos', verbose_name='Категория')),
                ('sent_contex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prima_Word.context_table', verbose_name='Контекст')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Постоянная Память - НеКорректные предложения.',
                'ordering': ['cat'],
            },
        ),
    ]
