# Generated by Django 4.0.1 on 2022-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prima_Word', '0009_trash_answers_incorrect_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence_Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(db_index=True, unique=True, verbose_name='Предложение')),
                ('sent_dech', models.TextField(verbose_name='Код-Дешифровка предложения')),
                ('grade', models.BooleanField(verbose_name='Бинарная Оценка')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Постоянная Память - Предложения',
                'ordering': ['sentence'],
            },
        ),
    ]
